### ISSUE TITLE
Time to upgrade Docker to v1.10.3 as the default Docker?

### ISSUE THREAD

**Issue by ailispaw** [bargees/barge-os#14]

**Comment by ailispaw** [comment]
It will make the ISO 1MB bigger, so it doesn't seem a big deal.

**Comment by nightscape** [comment]
Or maybe even 1.12 while you're at it? :smile:

**Comment by ailispaw** [comment]
I'm working at #16 with Docker v1.10.3.

**Comment by ailispaw** [comment]
Docker is getting bigger and bigger, and has multiple binaries since v1.11.
I will consider that later. :)
Thanks.

**Comment by ailispaw** [comment]
Close as #16
