### ISSUE TITLE
Barge Logo

### ISSUE THREAD

**Issue by ixkaito** [bargees/barge-os#17]
I made some logos. Which one do you prefer?

1.
![barge-logo-1](https://cloud.githubusercontent.com/assets/5457539/18139181/3ff263ae-6feb-11e6-9d16-ab39f8e11722.png)

2.
![barge-logo-2](https://cloud.githubusercontent.com/assets/5457539/18139184/3ff7d92e-6feb-11e6-8795-3d55814fd3b3.png)

3.
![barge-logo-3](https://cloud.githubusercontent.com/assets/5457539/18139183/3ff5a6b8-6feb-11e6-8b64-aa7623a79a8f.png)

4.
![barge-logo-4](https://cloud.githubusercontent.com/assets/5457539/18139182/3ff3f94e-6feb-11e6-9148-ebc676670bef.png)

**Comment by ailispaw** [comment]
Hi @ixkaito 
Wow, thank you so much!!
All look great. Hmm..

**Comment by ailispaw** [comment]
I like 2., but it is similar to https://www.bargeapp.com/ and its name is same.
We may had better put "OS" with the name.

**Comment by ixkaito** [comment]
Oh, what the hell! Let's avoid using No.2.
I was also considering to append "OS" but wanted to ask you, so it's just fine.

You like the taste of No.2? If so, I'll make some adjustments on it.

**Comment by ailispaw** [comment]
I have imagined a form of No.2, but all look great. But No.1 is too much, I guess.

**Comment by ailispaw** [comment]
2-> 1 -> 4 -> 3

**Comment by ailispaw** [comment]
No2. or No.4

**Comment by ailispaw** [comment]
I've come to like No.4 much.

```
     ____
    |    |
   /     |_________ _________ _________ _________ _________ ___________
  |      |    _ )  |    \    |    _ \  |    __|  |    __|  |          /
 /       |    _ \  |   _ \   |      /  |   (_ |  |    _|   |         /
|        |   ___/  | _/  _\  |   _|_\  |  \___|  |   ___|  |        /
~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^
```

**Comment by ixkaito** [comment]
This also can be an icon.
![barge-logo-4-icon](https://cloud.githubusercontent.com/assets/5457539/18169904/29779eda-7097-11e6-84a7-7ee3274c91d7.png)

Do you think we need "OS" for No.4? This font doesn't have lower case. It'd be better to change the font for "BargeOS".

**Comment by ailispaw** [comment]
The icon looks nice. I'm OK without "OS" for No.4. How do you think?

I'm going to release Barge 2.2.0 today.
I may want to add the ascii art into the login message. :)

**Comment by ailispaw** [comment]
<pre>
     ____
    |    |
   /     |_________ _________ _________ _________ _________ ___________
  |      |    _ )  |    \    |    _ \  |    __|  |    __|  |          /
 /       |    _ \  |   _ \   |      /  |   (_ |  |    _|   |         /
|        |   ___/  | _/  _\  |   _|_\  |  \___|  |   ___|  |        /
~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^
Welcome to Barge 2.2.0, Docker version 1.10.3, build 20f81dd
[bargee@barge ~]$ 
</pre>

Is this too much?

**Comment by ailispaw** [comment]
@ixkaito 
Anyway, I will create another repo for logo and invite you as a collaborator.

**Comment by ixkaito** [comment]
@ailispaw Thanks!

Maybe it's better to add "OS" for SEO. I made a "BargeOS" edition. What do you think about them.

![barge-logo-4a](https://cloud.githubusercontent.com/assets/5457539/18179715/c2178782-70be-11e6-9cd6-8bf36e7d5ed1.png)
![barge-logo-4b](https://cloud.githubusercontent.com/assets/5457539/18179716/c21b444e-70be-11e6-971c-02ca131180de.png)
![barge-logo-4c](https://cloud.githubusercontent.com/assets/5457539/18179717/c221226a-70be-11e6-8a86-b7b58912519d.png)

The ascii art will be fine. Maybe we should add it after we fix the logo.

**Comment by ailispaw** [comment]
Thanks.
I prefer the original one, but you can use "BARGE-OS" or "BARGE OS" as well.

I'm building 2.2.0 without the ascii art now.

**Comment by ixkaito** [comment]
OK. I'll push the data of the original one to the repo.

**Comment by ailispaw** [comment]
Thanks. Let's discuss there.

**Comment by ailispaw** [comment]
The final version.

![barge-logo-800x300](https://cloud.githubusercontent.com/assets/10327896/18331486/2ffa9ec0-7514-11e6-9e2a-be3d69a092bc.png)
