### ISSUE TITLE
LSI Logic SAS Support

### ISSUE THREAD

**Issue by tukiyo** [bargees/barge-os#25]
barge-2.3.1.isoでbootしたところ VMWare Player で SCSI DISKの認識がされません。
(CloudAtCost も VMWare + <s>SCSI</s> SASのようで同現象です。)

![barge](https://cloud.githubusercontent.com/assets/1517645/21298019/4d15ca8e-c5cd-11e6-9dd5-238d15547622.png)

* 以下はCloneZillaで起動した時のmoduleです。scsi_mod関連。こちらはDiskを認識しました。

![scsi_mod_ok](https://cloud.githubusercontent.com/assets/1517645/21298067/818d84cc-c5ce-11e6-8ce2-15360ad82dac.png)

* BargeOSには scsi_mod関連が含まれていない。

![scsi_mod2](https://cloud.githubusercontent.com/assets/1517645/21298068/84268206-c5ce-11e6-9624-af02a47f489d.png)

VirtualBoxでも同様に SCSI Diskは認識されませんでした。

![vboxscsi](https://cloud.githubusercontent.com/assets/1517645/21298159/0fb41ae4-c5d0-11e6-8413-61071c85839a.png)

**Comment by ailispaw** [comment]
ご要望ありがとうございます。
VMWare Player、CloudAtCost、CloneZilla でどのカーネル・モジュール／ドライバ（カーネル・パラメタ）が必要になるかご存知でしたら教えて頂けませんでしょうか？
あまり余計なモジュールを入れたくないので、最低限必要なものだけにしたいものですから。

現在は、基本的なSCSIパラメタのみカーネルにある状態で、
https://github.com/bargees/barge-os/blob/master/configs/kernel.config#L1319-L1407
```
CONFIG_SCSI_MOD=y
CONFIG_SCSI=y
CONFIG_SCSI_DMA=y
CONFIG_SCSI_LOWLEVEL=y
CONFIG_VMWARE_PVSCSI=y
```
はモジュールではなく、カーネル内にリンクされています。

SCSI ではなく、現在 VirtualBox や xhyve でサポートしている SATA や VIRTIO は指定不可能ということでしょうか？
それとも性能的に SCSI の方が良いということでしょうか？
よろしくお願いします。

**Comment by tukiyo** [comment]
返信ありがとうございます。
目的は CloudAtCost で利用することです。(VMWare Playerでは使う予定ありません。) 
CloudAtCost は VPSのため用意されたものを使うことしかできません。
LSISAS1068 (SCSIというかSASでした。)への対応は以下モジュールが必要かと思います。

```bash
$ lsmod  | grep sas
mptsas                 65536  2
mptscsih               40960  1 mptsas
mptbase               102400  2 mptsas,mptscsih
scsi_transport_sas     40960  1 mptsas
```

46ページ目
http://vmwgcomms.com/files/jp/pdf/workstation-pro-12-user-guide.pdf

![2016-12-19 11 41 40](https://cloud.githubusercontent.com/assets/1517645/21299561/2cab41b2-c5e0-11e6-8bf3-c58e2738d6a9.png)

以下は CloudAtCost 上のUbuntu 16.04 (4.4.0-36-generic) の出力となります。

```bash
$ dmesg | grep ioc0
[    2.240348] mptbase: ioc0: Initiating bringup
[    2.312648] ioc0: LSISAS1068 B0: Capabilities={Initiator}
[    2.483431] scsi host2: ioc0: LSISAS1068 B0, FwRev=01032920h, Ports=1, MaxQ=1
28, IRQ=18
[    2.506659] mptsas: ioc0: attaching ssp device: fw_channel 0, fw_id 0, phy 0,
 sas_addr 0x5000c298a1718859
...
```

ご検討お願いします。

**Comment by ailispaw** [comment]
なるほど、LSI Logic SAS となると、
```
CONFIG_FUSION=y
CONFIG_FUSION_SAS=y
```
になるでしょうか。

CloudAtCost でということですが、私の方でテストするとなると、アカウントを作らないとなりません。
CloudAtCost のメリットとかオススメはどういうところでしょうか？

**Comment by tukiyo** [comment]
CloudAtCostのメリットは今だと **たったの7ドルを1度払うだけでサービス終了まで使えます**  (月額制ではなく買い切り。)

![2016-12-19 13 26 05](https://cloud.githubusercontent.com/assets/1517645/21301209/ca093adc-c5ee-11e6-8b27-3bab101e48d7.png)

一応手順は[EasyBCDでwindows boot managerからISO bootし、windowsを消してRanchreOSをインストール - Qiita](http://qiita.com/tukiyo3/items/9c20c814f3b2c456e8b0)となりますが、適当なlinuxを入れてから以下でも大丈夫です。

`dd if=barge.iso of=/dev/sda; sync; reboot`

テストのisoイメージをUPいただければ私の方でCloudAtCostで動作テストいたします。

もしくはvmwareを使って.vmxを修正することで手元で確認できるようです。[参考](http://www.top-password.com/blog/vmware-change-scsi-controller-type-from-buslogic-to-lsi-logic/)

```diff
- scsi0.virtualDev = "lsilogic"
+ scsi0.virtualDev = "lsisas1068"
```

VMWare を使っているVPSはいくつかあるようで、以前調べたときはIDCFクラウドがVMWareでした。
[IDCFクラウドS1を月額220円運用 - Qiita](http://qiita.com/tukiyo3/items/a2953fe22c239eb28704)

**Comment by ailispaw** [comment]
$7 というのは凄いですね。パフォーマンスとか、使い勝手はどうですか？

手順ですが、

1. 標準の OS の中から適当なのを選んで、起動する。
2. VPS にログインする。
3. barge.iso をダウンロードする。
4. ハードディスクの中身を barge.iso で上書きする。
5. リブート

ということでしょうか？
EasyBCD での編集は Windows を選んだ場合ということですかね。

データ用に追加のディスクとかパーティションの変更とかは出来ますか？
カーネルの再構築は簡単ですが、boot 周りはちょっと工夫が入りそうな予感がします。

**Comment by tukiyo** [comment]
手順はそれであっています。

管理画面からDISKサイズ10GBを選んだら10GBのdiskが用意されますが、
windows7を選ぶと25GBのdiskが用意されるというメリットがあります。(空き容量10GB)
しかし最初はdebian8とか選ぶのが無難です。

```bash
1. Debian 8で起動
2. Debian 8にssh -p 22 root@ipaddress
3. wget barge.iso
4. dd if=barge.iso of=/dev/sda bs=1M;sync;sync;sync;
5. reboot
6. sudo fdisk /dev/sda
追加パーティションの作成。n p 2 Enter Enter Enter w
7. sudo mkfs.ext4 -L BARGE-DATA /dev/sda2; sudo reboot
```

> パフォーマンスとか、使い勝手はどうですか？

初代Raspberry PiくらいのDiskの遅さです。カナダにあるためネットワーク遅延もあります。(pingで168ms)
仮想マシンを作ってもネットワークに接続できないことが半々くらいです。（一度成功したらずっと成功する。）
よく管理画面に入れなくなったり、コンソール画面(noVNC)が接続失敗したりしますが値段を考えれば大したものです。

カーネルモジュールは以下が存在すれば良さそうです。
(Ubuntu16.10だとmptsasはカーネル内にリンクされていました。)

```bash
/lib/modules/`version`/kernel/drivers/message/fusion/mptsas.ko
/lib/modules/`version`/kernel/drivers/message/fusion/mptscsih.ko
/lib/modules/`version`/kernel/drivers/message/fusion/mptbase.ko
/lib/modules/`version`/kernel/drivers/scsi/scsi_transport_sas.ko
```

**Comment by ailispaw** [comment]
LSI Logic SAS をサポートしたものを作ってみました。
テストしてないので、本当にサポート出来ているか不安ですが、お試しください。
https://github.com/bargees/barge-os/commit/007ebd206c9252f1248fa6fee553d77550dbc7c3
https://github.com/bargees/barge-os/releases/tag/2.3.2-dev

**Comment by ailispaw** [comment]
> 初代Raspberry PiくらいのDiskの遅さです。カナダのためネットワーク遅延もあります。(pingで168ms)
> 仮想マシンを作ってもネットワークに接続できないことが半々くらいです。（一度成功したらずっと成功する。）
> よく管理画面に入れなくなったり、コンソール画面(noVNC)が接続失敗したりしますが値段を考えれば大したものです。

かなり厳しいですね。正式なサポートはちょっと考えさせて下さいｗ

**Comment by ailispaw** [comment]
ちなみに、
https://github.com/bargees/barge-os/blob/master/docs/build.md#building
の２つ目のマニュアルでのビルド方法であれば、Windows でも Linux でもビルドは可能のはずです。
ご自分でビルドされる場合は、
https://github.com/bargees/barge-os/commit/007ebd206c9252f1248fa6fee553d77550dbc7c3
のコミットをマージすれば良いかと思います。

**Comment by tukiyo** [comment]
早速の対応ありがとうございます。CloudAtCostで無事Disk認識しました。

<img width="727" alt="2016-12-19 15 14 17" src="https://cloud.githubusercontent.com/assets/1517645/21302868/d9f1be4c-c5fd-11e6-8e6f-4fb28a3eb420.png">

**Comment by ailispaw** [comment]
Barge は udev を使っていないので、ディスク周りのドライバは全てカーネルにリンクしています。

udev は関係無かったか？

**Comment by tukiyo** [comment]
以下ご報告です。

VMWare Playerでvmxファイルを以下修正した後起動するとDISK認識しました。
（修正しないと認識しなかった。修正前のコントローラは LSI53C1030）

```diff
- scsi0.virtualDev = "lsilogic"
+ scsi0.virtualDev = "lsisas1068"
```

また、VirtualboxでDISKコントローラをSAS指定してDISK認識しました。(LSISAS1068だった。)

**Comment by ailispaw** [comment]
ありがとうございます。
ちなみに、barge.img の方はどうでしょうか？
どちらかというとこちらの方が適しているかも知れません。
https://github.com/bargees/barge-os/blob/master/scripts/post_image.sh#L34-L67

**Comment by ailispaw** [comment]
`CONFIG_FUSION_SPI=y` も追加するといけそうです。＞LSI53C1030

**Comment by tukiyo** [comment]
barge.img を dd し reboot したところ以下のように無事認識しました。(VMWare Player + LSISAS1068)

![default](https://cloud.githubusercontent.com/assets/1517645/21303994/8e801820-c605-11e6-9859-c30ed7cec4f2.PNG)

**Comment by ailispaw** [comment]
barge.img のが良さげですね。

**Comment by tukiyo** [comment]
頂いた手順でbuild中です。 https://github.com/bargees/barge-os/blob/master/docs/build.md#building
macbook 12 のため処理速度が遅く、以下で30分くらい待っています。
一度完了したら次回はccacheが効いて早く終わるのかな

```
docker run --privileged -v /mnt/data/ccache:/build/buildroot/ccache \
  -v /vagrant/dl:/build/buildroot/dl --name barge-built barge-builder
```

**Comment by ailispaw** [comment]
最初は１時間前後かそれ以上、２回目からは３０分くらいだと思います。

**Comment by tukiyo** [comment]
ありがとうございました 🍣

**Comment by ailispaw** [comment]
Just release v2.3.2 with "Support LSI Logic SAS".
Thank you so much for your request.

LSI Logic SAS のみですが、リリースに含めることにしました。
ありがとうございました。

**Comment by tukiyo** [comment]
おお、助かります！

**Comment by ailispaw** [comment]
@tukiyo こちらはクローズしても良いでしょうか？

**Comment by tukiyo** [comment]
はい、ありがとうございました。

**Comment by ailispaw** [comment]
Thanks :)
