### ISSUE TITLE
/etc/resolv.conf について

### ISSUE THREAD

**Issue by tukiyo** [bargees/barge-os#26]
2.3.2-dev
ネットワーク設定は /etc/network/interfaces で 行うのかなと思いIPアドレスは固定されましたが、
/etc/resolv.conf には記述されませんでした。 (`/etc/init.d/S40network restart`)
そこで以下のように`cp /etc/resolv.conf.tail /etc/resolv.conf`を指定し乗り切りました。

```diff
 # interface file auto-generated by buildroot
 
 auto lo
 iface lo inet loopback
 
 auto eth0
 iface eth0 inet static
     address 192.168.1.93
     netmask 255.255.255.0
     gateway 192.168.1.1
-    dns-nameservers 8.8.8.8 8.8.4.4
+    post-up cp /etc/resolv.conf.tail /etc/resolv.conf
```

ところで /etc/resolv.conf が /tmp/resolv.conf にシンボリックリンクされているのは
何か事情がありますか。(DHCP用？)
というのも /tmp のため再起動すると消えてしまいます。

**Comment by ailispaw** [comment]
はい、`/etc/resolv.conf` は、DHCPCD という DHCP 用のパッケージが自動的に設定しているものですので、DHCP を使わない場合は、自由に変更しても構いません。
または、/etc/init.d/init.sh にスクリプトを仕込むと、
毎回起動時に実行されますし、固定で決め打ちでもかまわないと思います。
https://github.com/bargees/barge-os/blob/master/docs/customization.md#customizing-init-scripts-on-booting-up

**Comment by tukiyo** [comment]
ありがとうございました
