### ISSUE TITLE
/etc/init.d/S99custom の実行権限をつけ忘れて再起動すると起動しなくなる

### ISSUE THREAD

**Issue by tukiyo** [bargees/barge-os#27]
barge 2.3.4。 virtualboxにて確認。

```
sudo mkfs.ext4 -L BARGE-DATA /dev/sda
sudo reboot
```

/etc/init.d/S99custom に以下記述

```
pkg install vim
pkg install git
```

再起動すると以下発生。他のCDでbootして`chmod +x`にて復旧しました。

![barge](https://cloud.githubusercontent.com/assets/1517645/22227684/cdf104c6-e20f-11e6-8343-04639acd0281.png)

**Comment by ailispaw** [comment]
@tukiyo 
ご報告ありがとうございます。

なるほど、フェイルセーフを入れる必要がありますね。
考えてみます。

**Comment by ailispaw** [comment]
@tukiyo 

> 他のCDでbootしてchmod +xにて復旧しました。

`他のCDでboot` とはどのようなことでしょうか？

ちなみに、`S99custom` ですと、スクリプトのパラメタとして `start`/ `stop` をサポートしないと、
shutdown の時も起動してしまいます。
起動時だけなら、`/etc/init.d/start.sh` を使った方が簡単です。
https://github.com/bargees/barge-os/blob/master/docs/customization.md#customizing-init-scripts-on-booting-up

なお、カーネルの起動パラメタに `barge.debug` を追加するとデバッグモードとなり、エラーをスキップするようになります。（これは Vagrant box では難しいとは思いますが）

フェイルセーフする方法についてはまだ検討中です。

**Comment by tukiyo** [comment]
返信ありがとうございます。

他のCDでbootは、clonezillaのisoイメージでbootして、ファイルシステムをマウントし実行権限をつけました。

**Comment by ailispaw** [comment]
なるほど。ありがとうございます。

**Comment by ailispaw** [comment]
遅くなっていてすみません。かなり悩んでいます。

１．デバッグモードのように、エラーを単純にスキップする。
（エラーに気がつくのが難しくなりそう）
２．シングルユーザモードでシェルを起動させる。
（これが良さそうだけど、実装が難しそう。セキュリティ的にも）
３．このままの動作をデフォルトにする。
（デバッグモードで起動させるためのISOを別に用意する）

**Comment by tukiyo** [comment]
自分は1. が良いと思います。設定を間違えてもsshで対応を完結できるからです。

**Comment by ailispaw** [comment]
@tukiyo 
再度いろいろ検討した結果、
`/init` を完全にデバッグモードでエラーを無視するのではなく、
スクリプトの個々のエラーをスキップするようにしました。

なお、
今回のような目的のスクリプトは
`/etc/init.d/start.sh`
の方をお使い下さい。

issue のオープンありがとうございました。

**Comment by tukiyo** [comment]
ありがとうございます
