### ISSUE TITLE
Hyper-v Support Plan ?

### ISSUE THREAD

**Issue by guyschaos** [bargees/barge-os#35]
Hi @ailispaw , barge-os iso can boot with hyper-v, but seems no network interface. 
So, here is the question : Is there any plan to support hyper-v in this repo? Otherwise, just keep it simple and tiny ?
I've changed some kernel configs and built my image. Looks good with Hyper-V. Should I create a "Pull request" ?
Thanks again for your great work.

**Comment by ailispaw** [comment]
@guyschaos 
Thank you for opening the issue.

Mainly I want to keep it simple and tiny, but will welcome any PR.
Please let me see your configuration for Hyper-V.

I don't have a Windows machine here though... ;(

**Comment by ailispaw** [comment]
Close via #36
