### ISSUE TITLE
Boot stuck with version 2.4.1 

### ISSUE THREAD

**Issue by guyschaos** [bargees/barge-os#37]
Hi @ailispaw ,

Just test your latest release, v2.4.1. Can not boot with Hyper-V. Here is the screen capture.

![stuck](https://cloud.githubusercontent.com/assets/246671/23978348/85d56dca-0a2e-11e7-9bf7-e393b5e85c6f.PNG)

I've tried 3 isos. 
1. Your local test build for Hyper-V config. -- pass
2. My local test build for Hyper-V config. -- pass
3. v2.4.1  -- stuck

**Comment by ailispaw** [comment]
Hmm.
The differences from v2.4.1-dev are
kernel: Add CONFIG_X86_X2APIC 1ddf6967cb7bdc3c5790ffff4f47c5d3331b91d0
and
Upgrade kernel to v4.9.15 1ddf6967cb7bdc3c5790ffff4f47c5d3331b91d0 .

I guess it's not big different.

**Comment by ailispaw** [comment]
Hyper-V doesn't support x2APIC?

**Comment by guyschaos** [comment]
I have no idea. Maybe I can revert the commit and build on my local machine.

**Comment by ailispaw** [comment]
@guyschaos Which version of Windows do you use?

**Comment by guyschaos** [comment]
Is there any quick guide for building Barge with docker ? Vagrant will not be an option for me on my windows computer, because Hyper-V conflicts with VirtualBox,

**Comment by guyschaos** [comment]
@ailispaw  Windows 10 pro.

**Comment by ailispaw** [comment]
What you are trying to build is same as https://github.com/bargees/barge-os/pull/36#issuecomment-286566552 except the version number `2.4.1-dev`.

BTW,
`Asking for cache data failed` things are just a warning message and I can see in
https://github.com/bargees/barge-os/pull/36#issuecomment-286642352 as well.
There is something wrong somewhere else.

**Comment by guyschaos** [comment]
I've created a fresh VM,  it could boot without "_Asking for cache data failed_". I am confused...

**Comment by ailispaw** [comment]
I have never try this way, but it will work for you.

```
$ git clone https://github.com/bargees/barge-os.git
$ cd barge-os
<checkout a commit you want to build>
$ docker build -t barge-builder .
$ docker run --privileged --name barge-built barge-builder
$ docker cp barge-built:/build/buildroot/output/images/barge.iso .
```

**Comment by ailispaw** [comment]
> I've created a fresh VM, it could boot without "Asking for cache data failed". I am confused...

Ah..
It's strange...

**Comment by ailispaw** [comment]
I guess there may be some wrong cache in somewhere of Virtual HDD...

**Comment by guyschaos** [comment]
Yes, looks Virtual HDD related after doing some tests.
Exist VM:
1. boot with your local build , Physic HDD as Virtual HDD , pass
2. boot with your v2.4.1, Physic HDD as Virtual HDD , stuck
3. boot with your v2.4.1, Physic HDD as Virtual HDD and add a new Virtual HDD , pass... !!!

So, workaround is -- add a new Virtual HDD (will never be used.)...

**Comment by ailispaw** [comment]
Hmm.
There might be something wrong to umount the disks on shutdown.
Your shutdown process looks normal on Hyper-V?

**Comment by ailispaw** [comment]
Im not sure it's caused by x2APIC or kernel v4.9.15.
Can you disable x2APIC on Hyper-V VM to test?

**Comment by guyschaos** [comment]
Try to compile with docker. Vagrant only works on my Mac at home. Will tell you the test result ASAP.

**Comment by guyschaos** [comment]
@ailispaw 
After long long time of building, I got the iso of commit "Add CONFIG_X86_X2APIC ".
Remove my "New added fake Virtual HDD" , select the iso, boot the VM, every thing looks good.
Then, I tested the version 2.4.1, boot pass too.
That's weird. I have **not** change any thing else.
Maybe you can close this issue first. I will observe the Hyper-V barge-os behavior on my WIndows 10/WIndows Server 2012R2 these days.
Anyway, thanks for your support.

**Comment by ailispaw** [comment]
I found something.
Linux guest graceful shutdown in Hyper-V - Server Fault
http://serverfault.com/questions/747247/linux-guest-graceful-shutdown-in-hyper-v

We may need `modprobe hv_utils` and something (a user daemon).
I will try to create an ISO for that there. https://github.com/bargees/barge-packer/issues/11

Stay tuned.

**Comment by guyschaos** [comment]
All the iso (your local build, my local build, version 2.4.1 and so on) can boot without any workaround. And I have tested version 2.4.1 on my Hp Microserver gen8 (Windows server 2012 R2), everything looks good.
I cannot reproduce the "Asking for cache data failed" any more. Maybe, there is a mistake with my physic hdd.
The Hyper-V KVP daemon looks useful for Hyper-V users. I can test your build with KVP feature. Where is the download link ?

**Comment by ailispaw** [comment]
@guyschaos Thank you for the confirmation.

Here it is.
https://github.com/bargees/barge-packer/pull/12
