### ISSUE TITLE
/usr/bin/docker is 1.10.3

### ISSUE THREAD

**Issue by tnir** [bargees/barge-os#59]
Barge is now shipping /usr/bin/docker with Docker 1.10.3-based CLI. While there's no problem when profile loaded, errors may occur when profile is not loaded (e.g., ssh-command).

With Docker 1.10.3 CLI, we can't use some new docker commands (e.g., docker system df).

Currently PATH is overridden by [/etc/profile.d/optbin.sh](https://github.com/bargees/barge-os/blob/2.6.2/overlay/etc/profile.d/optbin.sh).

### /usr/bin/docker
```
/usr/bin/docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.7.6
 Git commit:   20f81dd
 Built:        Tue Oct 24 03:19:44 UTC 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
```

### /opt/bin/docker
```
/opt/bin/docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:39:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

<details>
<summary>OS info</summary>
<pre>
NAME="Barge"
VERSION=2.6.2
ID=barge
ID_LIKE=busybox
VERSION_ID=2.6.2
PRETTY_NAME="Barge 2.6.2"
HOME_URL="https://github.com/bargees/barge-os"
BUG_REPORT_URL="https://github.com/bargees/barge-os/issues"
</pre>
</details>

**Comment by ailispaw** [comment]
@tnir Thank you for opening and letting me know this issue.

Could you explain how to reproduce your problem?
What did you do exactly and what did you see when that happened?

Best regards

**Comment by ailispaw** [comment]
You may use like the following.

```
$ ssh bargee@xxx.xxx.xxx.xxx "bash -c 'which docker'"
/usr/bin/docker
```

Please use `-l` option to execute as a login session instead.

```
$ ssh bargee@xxx.xxx.xxx.xxx "bash -l -c 'which docker'"
/opt/bin/docker
```

**Comment by tnir** [comment]
@ailispaw You can produce this as you described as above. I (and some of users) don't want to use a workaround like using `-l` option and my main concern is why /usr/bin/docker is so old. Any reason to ship Docker 1.10 CLI in Barge OS?

**Comment by ailispaw** [comment]
@tnir
I understand your concern, but I want to keep Barge OS small, because that is one of main purposes of this project. After version 1.10.3, Docker binary is getting bigger and bigger.
That's why I've created a functionality for users to switch Docker versions easily.
However, I might consider to upgrade Docker some time in the future.

I will consider how we can omit `-l` option in the future.
Do you have any specific reason why you don't want to use the option?

Thank you and best regards,

**Comment by tnir** [comment]
@ailispaw You're right. Why don't we replace `/usr/bin/docker` with the symbolic link to `/etc/bin/docker` when a user installs other version (e.g., `17.09.0-ce` etc.) to `/etc/bin/docker`?

**Comment by ailispaw** [comment]
Because `/usr` is not persistent, but `/opt`,
`sudo /etc/init.d/docker restart 17.09.0-ce` installs Docker under `/opt/docker/<versions>/` and link it from `/opt/bin/docker`.

**Comment by ailispaw** [comment]
https://github.com/bargees/barge-os/pull/60 might help in the case of SSH, it's not perfect though.
