### ISSUE TITLE
Comparison with SkiffOS

### ISSUE THREAD

**Issue by paralin** [bargees/barge-os#8]
Hey guys,

Noticed your project today, was curious what your thoughts were about how it compares to my project SkiffOS?

http://github.com/paralin/skiffos

On a first glance:
- Skiff has a heavy focus on modularity and cross-platform (microcontroller) support
- Skiff allows for user-defined config plugins and has a very structured approach to configuration / compilation
- On default my Skiff system uses a ramdisk only to host Docker and does not allow for persistent package install in the host.

Any idea if we can merge efforts?

**Comment by ailispaw** [comment]
Hi @paralin ,
Thank you for stopping by.
Your project looks nice.

My project was originally intended to replace boot2docker which created a Docker environment on Mac/Windows (non-linux OS) desktop. It's clean, small and fast.
I have created the followings as well previously.
https://github.com/ailispaw/only-docker
https://github.com/ailispaw/rancheros-lite
https://github.com/ailispaw/docker-root

Actually I have just started thinking how I can forward it to other systems, such as cloud environments and hardwares/devices like yours.
So your project is very interesting for me, but it seems complicated for me.
I'm not sure what I can do for you.

**Comment by ailispaw** [comment]
You might know https://resin.io/.
They use https://www.yoctoproject.org/ as their host OS in a device.
Also I'm interested in those projects. FYI

**Comment by paralin** [comment]
Actually my project is much more simple than it seems...

What it is is a mechanism to set up modular configurations for Buildroot. So your repo here would be an example of one of those configurations. A config can have a root overlay, buildroot config fragments, kernel config fragments, hooks in the build cycle, resources, etc.

I plan to disassociate the embedded / dockerized elements from the config framework actually. But as is you could probably integrate your efforts into the repo just fine. 

I think yocto is a bit too much for what it does. Buildroot + a modular config package like mine is all you need.

**Comment by ailispaw** [comment]
I see.
So do you mean I can build Barge with your project as one of configurations under ./configs in your repo?

**Comment by paralin** [comment]
Yes. And the idea is that you could stick odroid/c2 in the config chain before it and immediately get it running on an odroid.

**Comment by ailispaw** [comment]
I understand that, I don't have any device to test though. :)
I will check your repo out deeply later.

**Comment by paralin** [comment]
It'd be interesting to make a base config for a general x86 system. I think the mastermind is almost that.

... actually afaik the asctec mastermind just takes a standard Ubuntu x86 install so we can probably just rename asctec/mastermind to x86_64/standard or something.

**Comment by prologic** [comment]
Stopping by because I'm looking for a more "lightweight" Rancher OS alternative -- Later versions of Rancher OS are becoming quite ridicoulous in how much memory footprint they require just to boot and at idle :/

**Comment by ailispaw** [comment]
@prologic Thank you for stopping by.
Any comments and suggestions would be appreciated.
Please feel free to open a new issue anytime.
Best regards,

**Comment by prologic** [comment]
We can close this right?

**Comment by paralin** [comment]
@prologic It would be trivial to run Rancher on Skiff, provided you have an arm distribution / are running on an x86 machine. Running most any other docker software is already easy.

Closing issue

**Comment by prologic** [comment]
I'm not interested in running Rancher but thanks :D

**Comment by paralin** [comment]
@prologic ah sorry, I'm not very familiar with rancher OS, I would have assumed it ran Rancher, and that was why you were asking for something that did functionally the same.

**Comment by prologic** [comment]
Nope; I run Rancher OS by itself -- not Rancher. In fact I believe Rancher
2.0 only works with Kubernetes anyway now; so I'm not sure why anyone would
be using Rancher OS + Rancher anymore... *shrugs*


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
