### ISSUE TITLE
Build: Drop Vagrant

### ISSUE THREAD

**Issue by prologic** [bargees/barge-os#81]
Please refactor the build system and drop Vagrant. It's an extra step that isn't necessary as we already use Docker to do the build. Assume anyone that develops/hacks on this already knows how to use `docker-machine` and `docker` :)

**Comment by ailispaw** [comment]
Thank you for your suggestion.

Sounds good.
It assumed that there was no docker environment in a local machine expect barge itself.

Let's make it CI/CD-friendly.

**Comment by prologic** [comment]
Honestly I *think* using Vagrant + Docker + some userspace is a bit too much!

Let's cut one of these things out -- Just assume the user isn't an idiot :)

**Comment by ailispaw** [comment]
Initially it was just for my personal use and my daily work with Vagrant on my Mac. :)

**Comment by prologic** [comment]
No worries :D These days I find Docker itself a good replacement to what Vagrant served -- That is a consistent development environment so you can ensure the same build every time.

**Comment by ailispaw** [comment]
I still love Vagrant much rather than docker-machine in a local dev environment though. :)

**Comment by ailispaw** [comment]
close via https://github.com/bargees/barge-os/pull/82
