### ISSUE TITLE
Project Goals

### ISSUE THREAD

**Issue by prologic** [bargees/barge-os#83]
Please describe the overall high-level project goals.

* What platforms does barge intend to target?
* What feature sets does barge intend to have? Which ones are non-goals?
* Which init systems fit barge's design?
* Are we sold on a busybox user-land?

**Comment by ailispaw** [comment]
The no.1 priority of this project is simple and small.

- What platforms does barge intend to target?  
  Initially it was for VirtualBox, but I would like to make it work at as many platform as possible.  
  I believe that it will make barge more usable in dev and real world under the same environment.

- What feature sets does barge intend to have? Which ones are non-goals?  
  It depends on the Container Ecosystem and its users, but keep it as simple as possible.  

- Which init systems fit barge's design?  
  I wrote my own init and pkg script with bash to keep it simple and for my study, but I don't hesitate to replace it with other one like finit and your pkgtools, if they fit my goal.

- Are we sold on a busybox user-land?  
  Not everything. If a busybox applet is a lack of functionality, it will be replaced with others, like bash, wget, dhcpcd and so on.
