### ISSUE TITLE
[feature request] release an image with wireguard integrated

### ISSUE THREAD

**Issue by diyism** [bargees/barge-os#90]
Since buildroot can integrate wireguard with "BR2_PACKAGE_WIREGUARD=y"(https://git.busybox.net/buildroot/tree/package/wireguard)
Could you release a BargeOS image with wireguard integrated?

Currently, i'm using barge.img 2.10.0 from https://github.com/bargees/barge-os/releases
and i can do "sudo pkg install wireguard", and it says: "barge-pkg-wireguard-2.10.0 has been installed into the system.", 
but when i exec "sudo modprobe wireguard" it says "modprobe: module wireguard not found in modules.dep".

**Comment by ailispaw** [comment]
@diyism Thank you for opening an issue and using Barge.

That's very interesting.

`pkg` command builds userspace binary only by default.

Let me try to figure out how to support it.

Thank you.

**Comment by ailispaw** [comment]
https://www.wireguard.com/install/#kernel-requirements

https://github.com/bargees/buildroot/blob/barge/package/wireguard/wireguard.mk#L36-L39

**Comment by diyism** [comment]
Great, do you have time to make a new BargeOS release image?

**Comment by ailispaw** [comment]
I'm trying to build a package file using `pkg` with `-e BR2_LINUX_KERNEL=y`, not a new OS image for now.
I will look into the package file and check if the kernel module is there.

```
$ wget https://raw.githubusercontent.com/bargees/barge-os/master/configs/kernel.config
$ sudo pkg build wireguard -v $(pwd)/kernel.config:/build/kernel.config \
-e BR2_LINUX_KERNEL=y \
-e BR2_LINUX_KERNEL_CUSTOM_VERSION=y \
-e BR2_LINUX_KERNEL_CUSTOM_VERSION_VALUE=\"4.14.68\" \
-e BR2_LINUX_KERNEL_VERSION=\"4.14.68\" \
-e BR2_LINUX_KERNEL_USE_CUSTOM_CONFIG=y \
-e BR2_LINUX_KERNEL_CUSTOM_CONFIG_FILE=\"/build/kernel.config\"
```

**Comment by diyism** [comment]
By the way, i'm using BargeOS on DigitalOcean vps, i think it's good for popularization of BargeOS, so i added the manual into README.md and made a pull request: https://github.com/bargees/barge-os/pull/91

**Comment by ailispaw** [comment]
I can see `/lib/modules/4.14.68-barge/extra/wireguard.ko`, but it seems we need `CONFIG_UNUSED_SYMBOLS` as well.

It looks like I have to build a new OS image with `CONFIG_UNUSED_SYMBOLS` anyway.
I will try it tomorrow.

**Comment by ailispaw** [comment]
https://github.com/torvalds/linux/blob/master/lib/Kconfig.debug#L253

> UNUSED_SYMBOLS
> Unused but exported symbols make the kernel needlessly bigger.  For
>  that reason most of these unused exports will soon be removed.  This
>  option is provided temporarily to provide a transition period in case
>  some external kernel module needs one of these symbols anyway. If you
>  encounter such a case in your module, consider if you are actually
>  using the right API.  (rationale: since nobody in the kernel is using
>  this in a module, there is a pretty good chance it's actually the
>  wrong interface to use).  If you really need the symbol, please send a
>  mail to the linux kernel mailing list mentioning the symbol and why
>  you really need it, and what the merge plan to the mainline kernel for
>  your module is.

Hmm.

**Comment by ailispaw** [comment]
I created a BargeOS with `CONFIG_UNUSED_SYMBOLS`.
It doesn't make the image bigger. That's good.
But I still get an error as below.

```
[bargee@barge ~]$ sudo modprobe wireguard
modprobe: can't load module wireguard (extra/wireguard.ko): unknown symbol in module, or unknown parameter
```

**Comment by ailispaw** [comment]
Finally I figured this out.
We don't need `CONFIG_UNUSED_SYMBOLS` in the kernel config for it.
But I built a wireguard package with its kernel module and there are some workarounds as below.

```
$ sudo pkg install kmod -e BR2_PACKAGE_KMOD_TOOLS=y
$ sudo pkg install wireguard
$ sudo depmod -a -b / $(uname -r)
$ sudo modprobe wireguard
$ lsmod
Module                  Size  Used by
wireguard             176128  0
ip6_udp_tunnel         12288  1 wireguard
udp_tunnel             12288  1 wireguard
```

Because i'm not familiar with wireguard, please test it and let me know the result.
Thank you.

**Comment by diyism** [comment]
Great, everything is ok now, huge thanks to you!

```
$ sudo pkg install kmod -e BR2_PACKAGE_KMOD_TOOLS=y
$ sudo pkg install wireguard
$ sudo depmod -a -b / 4.14.68-barge
$ sudo modprobe wireguard
$ lsmod | grep wireguard
wireguard             176128  0
ip6_udp_tunnel         12288  1 wireguard
udp_tunnel             12288  1 wireguard
$ sudo ip link add dev wg0 type wireguard
$ sudo ip addr add 10.0.0.6/32 dev wg0
$ sudo nano /etc/wireguard/wg0.conf    #to comment SaveConfig, Address, PostUp, PostDown
$ sudo wg setconf wg0 /etc/wireguard/wg0.conf
$ sudo ip link set wg0 up
$ sudo ip route add 10.0.0.0/24 dev wg0
$ ping 10.0.0.1
PING 10.0.0.1 (10.0.0.1): 56 data bytes
64 bytes from 10.0.0.1: seq=0 ttl=64 time=2.129 ms
64 bytes from 10.0.0.1: seq=1 ttl=64 time=1.632 ms
```
